# Configuración SonarCloud — Ecosistema SQA Equipo 58-1
# Reemplazar con los valores obtenidos en SonarCloud → Administration → General Settings
sonar.projectKey=odjaramillo_gestion-bibliotecaria-sqa
sonar.organization=odjaramillo

sonar.projectName=SQA - Gestion Bibliotecaria Equipo 58-1
sonar.projectVersion=1.0

# Rutas del código fuente
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Reporte de cobertura JaCoCo (disponible tras ejecutar mvn test jacoco:report)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusiones
sonar.exclusions=**/dto/**,**/config/**,**/*Application.java

# Encoding
sonar.sourceEncoding=UTF-8
